[0m17:16:15.804476 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015CBF4ECEF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015CBF4ED100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015CBF4ED1C0>]}


============================== 17:16:15.813628 | d787c601-6772-47f9-ae19-eb5d61a4c921 ==============================
[0m17:16:15.813628 [info ] [MainThread]: Running with dbt=1.7.7
[0m17:16:15.813628 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\pc\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:16:46.877859 [debug] [MainThread]: Starter project path: C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m17:16:46.923793 [info ] [MainThread]: 
Your new dbt project "SMA_BI" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:16:46.923793 [info ] [MainThread]: Setting up your profile.
[0m17:16:46.923793 [error] [MainThread]: Encountered an error:
mapping values are not allowed here
  in "C:\Users\pc\.dbt\profiles.yml", line 14, column 12
[0m17:16:47.071205 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 91, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\main.py", line 515, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 344, in run
    self.setup_profile(profile_name)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 250, in setup_profile
    if not self.check_if_can_write_profile(profile_name=profile_name):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 211, in check_if_can_write_profile
    profiles = yaml.safe_load(f) or {}
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "C:\Users\pc\.dbt\profiles.yml", line 14, column 12

[0m17:16:47.090956 [debug] [MainThread]: Command `dbt init` failed at 17:16:47.090956 after 31.35 seconds
[0m17:16:47.090956 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015CBF349B80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015CBF412F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015CBEF0ED80>]}
[0m17:16:47.105064 [debug] [MainThread]: Flushing usage events
[0m19:01:19.928438 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D71B5E12B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D71B8D6630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D71B8D5370>]}


============================== 19:01:19.944065 | 93b36c28-f341-49db-bf4a-5c4d000f0eb2 ==============================
[0m19:01:19.944065 [info ] [MainThread]: Running with dbt=1.7.7
[0m19:01:19.944065 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\pc\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug --profile prod', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:01:19.944065 [info ] [MainThread]: dbt version: 1.7.7
[0m19:01:19.944065 [info ] [MainThread]: python version: 3.12.2
[0m19:01:19.954868 [info ] [MainThread]: python path: C:\Users\pc\AppData\Local\Programs\Python\Python312\python.exe
[0m19:01:19.957772 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m19:01:19.959562 [info ] [MainThread]: Using profiles dir at C:\Users\pc\.dbt
[0m19:01:19.959562 [info ] [MainThread]: Using profiles.yml file at C:\Users\pc\.dbt\profiles.yml
[0m19:01:19.966624 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\pc\Documents\Dbt_Projet_Snowflake\Snow_Dbt\dbt_project.yml
[0m19:01:19.968616 [info ] [MainThread]: Configuration:
[0m19:01:19.970368 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m19:01:19.970368 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m19:01:19.970368 [info ] [MainThread]: Required dependencies:
[0m19:01:19.970368 [debug] [MainThread]: Executing "git --help"
[0m19:01:20.031406 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m19:01:20.032404 [debug] [MainThread]: STDERR: "b''"
[0m19:01:20.034398 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m19:01:20.037391 [info ] [MainThread]: Connection test skipped since no profile was found
[0m19:01:20.040113 [info ] [MainThread]: [31m2 checks failed:[0m
[0m19:01:20.041387 [info ] [MainThread]: dbt looked for a profiles.yml file in C:\Users\pc\.dbt\profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m19:01:20.050554 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\pc\Documents\Dbt_Projet_Snowflake\Snow_Dbt\dbt_project.yml> not found

[0m19:01:20.051551 [debug] [MainThread]: Command `dbt debug` failed at 19:01:20.051551 after 0.19 seconds
[0m19:01:20.058576 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D71B1243B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D71B40E510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D71B161190>]}
[0m19:01:20.060593 [debug] [MainThread]: Flushing usage events
